# Generated by Django 4.2.1 on 2023-05-29 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bid_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='placedbid', to=settings.AUTH_USER_MODEL)),
                ('biddedlist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listings')),
            ],
        ),
    ]
