# Generated by Django 4.2.1 on 2023-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comments_commenton'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentmade',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
