# Generated by Django 4.2.1 on 2023-05-30 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments_commentmade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentmade', models.CharField(blank=True, max_length=1000, null=True)),
                ('commentby', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL)),
                ('commenton', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='allcomment', to='auctions.listings')),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
